<a href="https://colab.research.google.com/github/ZataraHere/100-Days-of-Machine-Learning/blob/main/Numpy_100_questions_with_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.


In [3]:

#### 1. Import the numpy package under the name `np` (★☆☆)

import numpy as np


In [5]:

#### 2. Print the numpy version and the configuration (★☆☆)

print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

In [7]:
#### 3. Create a null vector of size 10 (★☆☆)

a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
#### 4. How to find the memory size of any array (★☆☆)

a = np.zeros(10)

print("Memory size of a is", a.size * a.itemsize, "bytes")

Memory size of a is 80 bytes


In [13]:

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [14]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

Z = np.zeros(10)
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [15]:

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

v = np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:

#### 8. Reverse a vector (first element becomes last) (★☆☆)

v = np.arange(10)
rev = v[::-1]
print(v, rev)

[0 1 2 3 4 5 6 7 8 9] [9 8 7 6 5 4 3 2 1 0]


In [21]:

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

a = np.nonzero([1,2,0,0,4,0])
a

(array([0, 1, 4]),)

In [29]:

#### 11. Create a 3x3 identity matrix (★☆☆)
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:

#### 12. Create a 3x3x3 array with random values (★☆☆)

a = np.random.rand(3,3,3)
a

array([[[-1.1572269 ,  0.68579274,  0.67618725],
        [ 0.39762102,  0.26993583, -0.20512888],
        [ 0.60285094, -1.68697181, -1.2181466 ]],

       [[-0.45705636,  0.98901753, -1.21985639],
        [ 0.77155824, -0.26309093,  0.77453391],
        [ 0.16445619, -0.28043116,  1.14388433]],

       [[ 0.58571436, -2.46075351,  2.22710153],
        [ 1.50305272,  0.59584024, -2.4432404 ],
        [-0.60051977, -0.89922538, -3.1391647 ]]])

In [32]:

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
a = np.random.randn(10,10)
print("Max:", a.max(), "Min:", a.min())

Max: 3.040020325464174 Min: -2.1598927377828705
